### ISSUE TITLE
RN50 pretrained backbone

### ISSUE THREAD

**Issue by priyamdey** [amazon-research/long-short-term-transformer#1]
Hi. Thanks for sharing the codebase of LSTR. I was unable to get hold of [this](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/tsn_r50_320p_1x1x8_100e_kinetics400_rgb.py) Kinetics-pretrained RN50 checkpoint which you have mentioned in your readme. It would be quite helpful if you could share this pretrained backbone (and if possible, for ActivityNet too). 

Thanks.

**Comment by xumingze0308** [comment]
To get this checkpoint, you need to open this page (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/README.md), then find the checkpoint by name (tsn_r50_320p_1x1x8_100e_kinetics400_rgb).

For the ANet one, you can find it in this page (https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsn/README.md#activitynet-v13).
