### ISSUE TITLE
How to extract perframe features using mmaction2?

### ISSUE THREAD

**Issue by Prot-debug** [amazon-research/long-short-term-transformer#11]
Hi,

I'm a beginner of video understanding and OAD. I have installed mmaction2 and denseflow, it works well. But I'm not sure how to extract perframe features using it.

1. Is there any ready-made apis to solve the above problem? I've taken much time to search the solutions, but I didn't find.
2. If no ready-made apis, could you plz share related codes with us? It's important for beginners.

Thank you for your awesome repo. And hope your reply.

**Comment by xumingze0308** [comment]
You could directly use the features and targets here: https://github.com/zhaoyue-zephyrus/TeSTra. Please check our latest readme for details.

**Comment by rickywrq** [comment]
@Prot-debug Have you figured out how to extract features? 
@xumingze0308 Could you please release more information about feature extraction? Given that LSTR is considered as the SOTA method, it is essential for others to reproduce the results and apply LSTR to other datasets.

**Comment by jun297** [comment]
@rickywrq Hi, have you figured out how to extract features?
