### ISSUE TITLE
About the activitynet features.

### ISSUE THREAD

**Issue by sqiangcao99** [amazon-research/long-short-term-transformer#14]
Hi, 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/73031357/184647345-c2d13955-de1f-4647-95ca-e2d928bead97.png">
For ActivityNet pre-trained model, which two configuration files are used for rgb and flow?

**Comment by xumingze0308** [comment]
We used the "clip_rgb" ones. You can also directly use the feature from [TeSTra](https://github.com/zhaoyue-zephyrus/TeSTra).

**Comment by sqiangcao99** [comment]
@xumingze0308. Hi, thanks for your help. Currently, I have some proplems reproducing the resulting the results(6% lower) on TVSeries using the ActivityNet pretrained features. 
Specifically, 
1. I extract the rgb frames with resolution of short-side 320 and flows with resolution of 340X256;
2. The rgb frames and flow frams are preprocessed according to the config file of mmaction2, which is 
```
    # RGB
    data_pipeline = [
        dict(type='RawFrameDecode'), 
        dict(type='CenterCrop', crop_size=256),
        dict(type='Normalize', **args.img_norm_cfg),
        dict(type='FormatShape', input_format='NCHW'),
        dict(type='Collect', keys=['imgs'], meta_keys=[]),
        dict(type='ToTensor', keys=['imgs']), 
    ]

    data_pipeline = [
        dict(type='RawFrameDecode'),
        dict(type='Resize', scale=(-1, 256)),
        dict(type='TenCrop', crop_size=224),
        dict(type='Normalize', **args.img_norm_cfg),
        dict(type='FormatShape', input_format='NCHW_Flow'),
        dict(type='Collect', keys=['imgs'], meta_keys=[]),
        dict(type='ToTensor', keys=['imgs'])
]
```
3. The extracting code is modified based on https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/tsn_feature_extraction.py. 

Is the whole process correct?

**Comment by xumingze0308** [comment]
For both rgb and flow, we don't conduct CenterCrop, but directly use the default resolution.

**Comment by Juice-zz** [comment]
> 你好， <img alt="image" width="933" src="https://user-images.githubusercontent.com/73031357/184647345-c2d13955-de1f-4647-95ca-e2d928bead97.png">对于ActivityNet预训练模型，rgb和flow使用哪两个配置文件？

hi,can you share the website address of the activitynet pretained model for me?

**Comment by Juice-zz** [comment]
> [@xumingze0308](https://github.com/xumingze0308)。嗨，谢谢你的帮助。目前，我在使用 ActivityNet 预训练功能在 TVSeries 上重现结果（降低 6%）时遇到了一些问题。具体来说，
> 
> 1. 我提取了短边分辨率为320的rgb帧和分辨率为340X256的流；
> 2. 根据 mmaction2 的配置文件对 rgb 帧和流帧进行预处理，该文件为
> 
> ```
>     # RGB
>     data_pipeline = [
>         dict(type='RawFrameDecode'), 
>         dict(type='CenterCrop', crop_size=256),
>         dict(type='Normalize', **args.img_norm_cfg),
>         dict(type='FormatShape', input_format='NCHW'),
>         dict(type='Collect', keys=['imgs'], meta_keys=[]),
>         dict(type='ToTensor', keys=['imgs']), 
>     ]
> 
>     data_pipeline = [
>         dict(type='RawFrameDecode'),
>         dict(type='Resize', scale=(-1, 256)),
>         dict(type='TenCrop', crop_size=224),
>         dict(type='Normalize', **args.img_norm_cfg),
>         dict(type='FormatShape', input_format='NCHW_Flow'),
>         dict(type='Collect', keys=['imgs'], meta_keys=[]),
>         dict(type='ToTensor', keys=['imgs'])
> ]
> ```
> 
> 3. 提取代码基于https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/tsn_feature_extraction.py进行修改。
> 
> 整个过程正确吗？

Have you improved your map? I followed this method and there was a 6% difference. I would be extremely grateful if you could share your method.
