### ISSUE TITLE
about custom dataset

### ISSUE THREAD

**Issue by tghim** [amazon-research/long-short-term-transformer#15]
Thank you to share your great work! 

I have something to ask you.

I have my own dataset that I want to apply your LSTR to, and for this I did feature extraction for rgb and flow respectively according to this [https://github.com/open-mmlab/mmaction2/tree/master/tools/data/activitynet](url). However, the feature results came out in pkl format. To use your dataloader, it must be in npy format. How can I get the features out in npy format like you?

**Comment by xumingze0308** [comment]
You just need to convert the feature of each video from .pkl into a single .npy file. The feature should be in shape of L x C, where L is the length of the video and C is the feature dimension of each frame. You can refer the readme for details.

**Comment by tghim** [comment]
Thank you for your reply!
