### ISSUE TITLE
Link for BN-Inception

### ISSUE THREAD

**Issue by jbistanbul** [amazon-research/long-short-term-transformer#19]
Thank you for your great work! I am trying to extract features by myself and the link for BN-Inception is currently not working. Could you please update the link? Thank you so much!

**Comment by xumingze0308** [comment]
The authors deleted the one that I used for whatever reasons. But you can refer to the pre-trained weights here: https://drive.google.com/drive/folders/1R4n8vSQJ0LtB1mPhhjMHEQrKj3UDQS1U.

**Comment by xumingze0308** [comment]
The PyTorch code of BN-Inceptioin can be found here: https://github.com/amazon-science/stochastic-backpropagation/blob/cvpr2022/src/lstr/models/backbones/bninception.py.

**Comment by jbistanbul** [comment]
Thank you so much!

**Comment by z-w-wang** [comment]
Why conv1_7x7_s2.weight is shape torch.Size([64, 10, 7, 7]) instead of ([64, x, 7, 7]) (x <= 3) ?
