### ISSUE TITLE
Some details about the feature extraction.

### ISSUE THREAD

**Issue by sqiangcao99** [amazon-research/long-short-term-transformer#2]
Hi, thanks for generously sharing your code. When I try to extract optical flow features of Kinetic using BNInception, I encountered some problems.
* I don't know the data preprocessing method for BNInception. Could you please provide a more complete code?
* I notice there are some configurations to extract optical flow using denseflow. Which configuration of denseflow did you use? Such as: `denseflow test.avi -b=20 -a=tvl1 -s=1 -v`?

**Comment by xumingze0308** [comment]
Hi, we cannot release the code related to data, and we used the same configuration  of denseflow as you shared.

**Comment by sqiangcao99** [comment]
Besides, I notice the input channel of the BNinception is 10. Did you drop the optical flows of the first frame in a video chunk that has the size of 6?

**Comment by xumingze0308** [comment]
The optical flow is computed between two adjacent frames. Then, a video chunk of 6 frames will output 5 optical flow images, each with x and y channels.

**Comment by sqiangcao99** [comment]
Hi. When I use the image transform code bellow to extract the flow feature, the elements of the feature vector are almost all 0. Is this normal？ 
```python
clip_mean = [0.5, 0.5] * flow_length # mean for flow_x and flow_y, flow_length is 5
clip_std = [0.226, 0.226] * flow_length
normalize = video_transforms.Normalize(mean=clip_mean, std=clip_std)
flow_transform = video_transforms.Compose([
    video_transforms.Scale((256)), 
    video_transforms.CenterCrop((224)),
    video_transforms.ToTensor(),
    normalize,
])
```
the feature vector
```
[0., 0., 0., ..., 0., 0., 0.], # almost 163 none-zero elements.
```

**Comment by sqiangcao99** [comment]
When I try to reproduce the results on THUMOS. There are 314 iterations for training, 354 iterations for testing, and 696 iterations for batch inference at the default settings. Are these the same as yours?

**Comment by xumingze0308** [comment]
Yes.

**Comment by LukasHedegaard** [comment]
Hi @xumingze0308 , thanks for sharing the codebase.
A few followup questions regarding the preparation of flow features:

1) How did you resize the optical flow frames prior to processing with BNInception? Resize the shortest side to 224 and then center-crop 224x224?

2) BNInception with (10, 224, 224) inputs produces (1024, 7, 7) outputs. Did you use average pool over the 7x7 spatial dimensions?

3) As input to the BNInception block, did you stack 5 flow_x then 5 flow_y (i.e. [x,x,x,x,x,y,y,y,y,y], or did you interleave them (i.e. [x,y,x,y,x,y,x,y,x,y])

**Comment by xumingze0308** [comment]
1. We didn't resize the image, which should be in size of 320x180 in THUMOS, but used 10 crops following https://github.com/yjxiong/action-detection/blob/master/transforms.py.
2. Yes, we used average pooling.
3. We used [x,y,x,y,x,y,x,y,x,y].
