### ISSUE TITLE
Link Failure

### ISSUE THREAD

**Issue by TapiocaQAQ** [amazon-research/long-short-term-transformer#23]
Hello, For Data Preparation, "For Kinetics pretrained features, we use the [ResNet-50] model for the RGB inputs. We recommend to use this [checkpoint] in [MMAction2]. We use the [BN-Inception] model for the optical flow inputs. We recommend to use the model [here]."

The link of recommend model of [BN-lnception] for optical flow was Failure,

**Comment by z-w-wang** [comment]
Have you solved this question?

**Comment by Prism-hua** [comment]
Hello @TapiocaQAQ , I have encountered the same problem with you. I am writing to ask whether you have solved that problem or. If yes, I sincerely hope that you can share the solution with me. Thanks a lot!

**Comment by Juice-zz** [comment]
> 您好，我遇到了您的问题。我写信问您是否解决了这个问题。如果是，我衷心希望您能与我分享解决方案。多谢！

"Can you share the BN-Inception model you are using?"
