### ISSUE TITLE
How to handle imbalance in dataset for TVSeries?

### ISSUE THREAD

**Issue by miteshksingh** [amazon-research/long-short-term-transformer#6]
Hi,

Thanks for the awesome code repo.
I observed that there is a large imbalance in dataset. For TVSeries, >70% of data is background class.

1. I was wondering if you tried any technique to deal with the imbalance in the dataset? The LSTR paper does not mention any such technique. 
 
2. My validation loss does not converge and most predictions are of background class. My mcAP does not increase over epochs. What metric do you recommend to track/debug over epochs for performance of non-background classes on TVSeries? 

Thanks!

**Comment by xumingze0308** [comment]
1. No, we haven't. This is common problem in many action tasks, but is not the focus of LSTR. Ideally, a good solution to imbalance could further boost LSTR's performance.

2. For TVSeries, we just used mcAP for evaluation. There could be some bugs or problems of features, if your validation loss cannot converge.
