### ISSUE TITLE
Some details about preparing dataset.

### ISSUE THREAD

**Issue by Echo0125** [amazon-research/long-short-term-transformer#9]
Hi, thank you for sharing the code, I met some problems when I prepare the dataset.
1. I want to know how you extract the feature of TVSeries？ Is the input image the original size? Did you do any crop or resize?

2. I get the target_perframe.npy on the frame-level. For example, if one video time is 200 seconds, FPS is 4, the frame of the video is 800, I get the annotation by .txt and transfer the seconds in the annotaion to frames (by multiply the FPS), and for each frame, if any action happens in this frame,this action corresponds to the value in the vector will plus one. Finally I will get a 800 x number of classes's array. Is there any mistake in my operation?

3. Would you please share the training log so thao I can compare it with my log?

**Comment by xumingze0308** [comment]
Hi,

The input size is scaled to 340x256. We extracted the features using bninception, and do multi-crop following https://github.com/yjxiong/action-detection/blob/master/transforms.py. For now, I didn't see any problem from your descriptions to generate the target.

**Comment by Echo0125** [comment]
Thanks！

**Comment by Prot-debug** [comment]
@Wangjh0125 
Hi Wangjh0125 ，

I followed the `url` [https://github.com/yjxiong/action-detection/blob/master/transforms.py](url) that author mentionded in this issue. But I found that this data preprocessing is so inefficient, that is, processing one `.jpg` files frame by frame. And it's easy to cause memory leak problems by using the function `PIL.Image.open()`.
I don't know where I am going wrong, my code process is as follows. Could you give me some advice plz?

```
def transforms_img(img_list):

    trans = torchvision.transforms.Compose([
        GroupScale(256),
        GroupRandomCrop(224),
        Stack(),
        ToTorchFormatTensor(),
        GroupNormalize(
            mean=[128],
            std=[128]
        )]
    )

    for i, img_dir in enumerate(img_list):
        with open(img_dir, 'rb') as open_file:
            img = Image.open(open_file).convert('L')
            color_group = [img]
            rst = trans(color_group)
            del color_group
            del img
        if i == 0:
            stack_img = rst
            del rst
        else:
            stack_img = torch.cat((stack_img, rst), dim=0)
            del rst
    gc.collect() 

```

**Comment by chcchc97** [comment]
@Echo0125 Hi! what does ' the value in the vector' refer to?
![image](https://github.com/amazon-science/long-short-term-transformer/assets/60684460/0a962f09-d1a5-4107-bf05-f9ef59154ef4)

**Comment by EricLina** [comment]
> Hi, thank you for sharing the code, I met some problems when I prepare the dataset.
> 
> 1. I want to know how you extract the feature of TVSeries？ Is the input image the original size? Did you do any crop or resize?
> 2. I get the target_perframe.npy on the frame-level. For example, if one video time is 200 seconds, FPS is 4, the frame of the video is 800, I get the annotation by .txt and transfer the seconds in the annotaion to frames (by multiply the FPS), and for each frame, if any action happens in this frame,this action corresponds to the value in the vector will plus one. Finally I will get a 800 x number of classes's array. Is there any mistake in my operation?
> 3. Would you please share the training log so thao I can compare it with my log?

Hello, can you share the code preparing for TVSeries? Thank you very much.
